title: Let's Get Fancy
author: RexRowan
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Ain't it the finest site in the universe!

# social links
twitter_username: your-twitter-handle EINoctem
github_username:  your-github-handle RexRowan

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
